version: '3.8'

# Production overrides
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_production_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-production-jwt-secret-change-me}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-production-refresh-secret-change-me}
      DATABASE_URL: postgresql://after_sales_user:${POSTGRES_PASSWORD:-secure_production_password}@postgres:5432/after_sales_db?schema=public
      LOG_LEVEL: warn
    restart: always
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      args:
        REACT_APP_API_URL: /api
    restart: always

  nginx:
    profiles: []  # Enable nginx in production
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /var/log/nginx:/var/log/nginx
    restart: always
