[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_VERSION = '18'
NPM_CONFIG_PRODUCTION = 'false'
